apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world
  namespace: argocd
spec:
  destination:
    namespace: argocd
    name: kind
  project: default
  source:
    path: umbrella-chart
    repoURL: https://github.com/prakrit55/argocd-umbrellaHelm.git
    targetRevision: HEAD
    helm:
      # https://argo-cd.readthedocs.io/en/stable/user-guide/helm/#values-files
      valueFiles:
      - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
